// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkPHYS : PngChunk {
		// http://www.w3.org/TR/PNG/#11pHYs
		public long pixelsxUnitX;
		public long pixelsxUnitY;
		public int units; // 0: unknown 1:metre
	
		public PngChunkPHYS(ImageInfo info) : base(Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.pHYs_TEXT, info) {
		}
	
		public override ChunkRaw CreateChunk() {
			ChunkRaw c = CreateEmptyChunk(9, true);
			Ar.Com.Hjg.Pngcs.PngHelper.WriteInt4tobytes((int) pixelsxUnitX, c.data, 0);
			Ar.Com.Hjg.Pngcs.PngHelper.WriteInt4tobytes((int) pixelsxUnitY, c.data, 4);
			c.data[8] = (byte) units;
			return c;
		}
	
		public override void ParseFromChunk(ChunkRaw chunk) {
			if (chunk.len != 9)
				throw new PngjException("bad chunk length " + chunk);
			pixelsxUnitX = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt4fromBytes(chunk.data, 0);
			if (pixelsxUnitX < 0)
				pixelsxUnitX += 0x100000000L;
			pixelsxUnitY = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt4fromBytes(chunk.data, 4);
			if (pixelsxUnitY < 0)
				pixelsxUnitY += 0x100000000L;
			units = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt1fromByte(chunk.data, 8);
		}
	
		// returns -1 if not in meters, or not equal
		public double GetAsDpi() {
			if (units != 1 || pixelsxUnitX != pixelsxUnitY)
				return -1;
			return ((double) pixelsxUnitX) * 0.0254d;
		}
	
		public void SetAsDpi(double dpi) {
			units = 1;
			pixelsxUnitX = (long) (dpi / 0.0254d + 0.5d);
			pixelsxUnitY = pixelsxUnitX;
		}
	
		public override void CloneDataFromRead(PngChunk other) {
			PngChunkPHYS otherx = (PngChunkPHYS) other;
			this.pixelsxUnitX = otherx.pixelsxUnitX;
			this.pixelsxUnitY = otherx.pixelsxUnitY;
			this.units = otherx.units;
		}
	}
}
