// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkIDAT : PngChunk {
		// http://www.w3.org/TR/PNG/#11IDAT
		// This is dummy placeholder - we write/read this chunk (actually several)
		// by special code.
		public PngChunkIDAT(ImageInfo i) : base(Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.IDAT_TEXT, i) {
		}
	
		public override ChunkRaw CreateChunk() {// does nothing
			return null;
		}
	
		public override void ParseFromChunk(ChunkRaw c) { // does nothing
		}
	
		public override void CloneDataFromRead(PngChunk other) {
		}
	}
}
