// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkIEND : PngChunk {
		// http://www.w3.org/TR/PNG/#11IEND
		// this is a dummy placeholder
		public PngChunkIEND(ImageInfo info) : base(Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.IEND_TEXT, info) {
		}
	
		public override ChunkRaw CreateChunk() {
			ChunkRaw c = new ChunkRaw(0, Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.IEND, false);
			return c;
		}
	
		public override void ParseFromChunk(ChunkRaw c) {
			// this is not used
		}
	
		public override void CloneDataFromRead(PngChunk other) {
		}
	}
}
