// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public abstract class PngChunkTextVar : PngChunk {
		protected internal String key; // key/val: only for tEXt. lazy computed
		protected internal String val;
	
		protected internal PngChunkTextVar(String id, ImageInfo info) : base(id, info) {
		}
	
		public class PngTxtInfo {
			public String title;
			public String author;
			public String description;
			public String creation_time;// = (new Date()).toString();
			public String software;
			public String disclaimer;
			public String warning;
			public String source;
			public String comment;
			/*
			 * public void writeChunks() { writeChunk("Title", title);
			 * writeChunk("Author", author); writeChunk("Description", description);
			 * writeChunk("Creation Time", creation_time); writeChunk("Software",
			 * software); writeChunk("Disclaimer", disclaimer); writeChunk("Software",
			 * software); writeChunk("Warning", warning); writeChunk("Source", source);
			 * writeChunk("Comment", comment); }
			 */
			/*
			 * private void writeChunk(String name, String val) { if (val == null)
			 * return; PngChunk p = PngChunk.createTextChunk(name, val, crcEngine);
			 * p.writeChunk(os); }
			 */
		}
	
		public String GetKey() {
			return key;
		}
	
		public String GetVal() {
			return val;
		}
	}
}
