// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace pgncstest {
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class MyTests {
		public static void Test1() {
			pgncstest.DecreaseRed.DecreaseRedChannel("/temp/patron2.png", "/temp/patron2z.png");
		}
	
		public static void Run(String[] args) {
			Test1();
		}
	}
}
