// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace pgncstest {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class ShowInfo {
		/*
		 * public static void show(File file, boolean includeChunksSkel) { PngReader
		 * pngr = FileHelper.createPngReader(file);
		 * System.out.println(pngr.toString()); for (int row = 0; row <
		 * pngr.imgInfo.rows; row++) { pngr.readRow(row); } pngr.end();
		 * if(includeChunksSkel) pngr.showChunks(); }
		 */
		public static void Show2(string file, bool includeChunksSkel) {
			PngReader pngr = FileHelper.CreatePngReader(file);
			for (int row = 0; row < pngr.imgInfo.rows; row++) {
				pngr.ReadRow(row);
			}
			pngr.End();
			System.Console.Out.WriteLine(pngr.ToString());
			pngr.PrintFoundChunks();
			if (includeChunksSkel)
				System.Console.Out.WriteLine(pngr.chunks.ToString());
		}
	
		public static void Run(String[] args) {
			/*
			 * if (args.length != 1) { System.err.println("Arguments: [pngsrc]");
			 * System.exit(1); }
			 */
			Show2("c:\\temp\\test\\pp0n2c16.png", true);
			// show2(new File("c:\\temp\\test\\tbbn3p08z.png"), true);
		}
	
		public static void Print(int x) {
			System.Console.Out.WriteLine(x);
		}
	}
}
