// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Ar.Com.Hjg.Pngcs.Chunks
{

    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public enum ChunkLoadBehaviour
    {
        // what to do with non critical chunks when reading?
        LOAD_CHUNK_NEVER, /* ignore non-critical chunks */
        LOAD_CHUNK_KNOWN, /* load chunk if 'known' */
        LOAD_CHUNK_IF_SAFE, /* load chunk if 'known' or safe to copy */
        LOAD_CHUNK_ALWAYS, /* load chunk always */

    }
}
