// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkTIME : PngChunk {
		// http://www.w3.org/TR/PNG/#11tIME
		public int year, mon, day, h, m, s;
	
		public PngChunkTIME(ImageInfo info) : base(Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.tIME_TEXT, info) {
		}
	
		public override ChunkRaw CreateChunk() {
			ChunkRaw c = CreateEmptyChunk(7, true);
			Ar.Com.Hjg.Pngcs.PngHelper.WriteInt2tobytes(year, c.data, 0);
			c.data[2] = (byte) mon;
			c.data[3] = (byte) day;
			c.data[4] = (byte) h;
			c.data[5] = (byte) m;
			c.data[6] = (byte) s;
			return c;
		}
	
		public override void ParseFromChunk(ChunkRaw chunk) {
			if (chunk.len != 7)
				throw new PngjException("bad chunk " + chunk);
			year = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt2fromBytes(chunk.data, 0);
			mon = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt1fromByte(chunk.data, 2);
			day = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt1fromByte(chunk.data, 3);
			h = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt1fromByte(chunk.data, 4);
			m = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt1fromByte(chunk.data, 5);
			s = Ar.Com.Hjg.Pngcs.PngHelper.ReadInt1fromByte(chunk.data, 6);
		}
	
		public override void CloneDataFromRead(PngChunk other) {
			PngChunkTIME x = (PngChunkTIME) other;
			year = x.year;
			mon = x.mon;
			day = x.day;
			h = x.h;
			m = x.m;
			s = x.s;
		}
	
		public void SetNow(int secsAgo) {
            DateTime d1 = DateTime.Now;
            year = d1.Year;
            mon = d1.Month;
            day = d1.Day;
            h = d1.Hour;
            m = d1.Minute;
            s = d1.Second;
		}
	}
}
