// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkIHDR : PngChunkSingle {
        public const String ID = ChunkHelper.IHDR;
		public int cols;
		public int rows;
		public int bitspc;
		public int colormodel;
		public int compmeth;
		public int filmeth;
		public int interlaced;
	
		// http://www.w3.org/TR/PNG/#11IHDR
		//
		public PngChunkIHDR(ImageInfo info) : base(ID, info) {
		}

        public override ChunkOrderingConstraint GetOrderingConstraint()
        {
            return ChunkOrderingConstraint.NA;
        }
	
		public override ChunkRaw CreateRawChunk() {
			ChunkRaw c = new ChunkRaw(13, ChunkHelper.b_IHDR, true);
			int offset = 0;
			Ar.Com.Hjg.Pngcs.PngHelperInternal.WriteInt4tobytes(cols, c.Data, offset);
			offset += 4;
			Ar.Com.Hjg.Pngcs.PngHelperInternal.WriteInt4tobytes(rows, c.Data, offset);
			offset += 4;
			c.Data[offset++] = (byte) bitspc;
			c.Data[offset++] = (byte) colormodel;
			c.Data[offset++] = (byte) compmeth;
			c.Data[offset++] = (byte) filmeth;
			c.Data[offset++] = (byte) interlaced;
			return c;
		}
	
		public override void ParseFromRaw(ChunkRaw c) {
			if (c.Length != 13)
				throw new PngjException("Bad IDHR len " + c.Length);
			MemoryStream st = c.GetAsByteStream();
			cols = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadInt4(st);
			rows = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadInt4(st);
			// bit depth: number of bits per channel
			bitspc = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadByte(st);
			colormodel = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadByte(st);
			compmeth = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadByte(st);
			filmeth = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadByte(st);
			interlaced = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadByte(st);
		}
	
		public override void CloneDataFromRead(PngChunk other) {
			PngChunkIHDR otherx = (PngChunkIHDR) other;
			cols = otherx.cols;
			rows = otherx.rows;
			bitspc = otherx.bitspc;
			colormodel = otherx.colormodel;
			compmeth = otherx.compmeth;
			filmeth = otherx.filmeth;
			interlaced = otherx.interlaced;
		}
	}
}
