// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	/*
	 */
	public class PngChunkGAMA : PngChunkSingle {
		// http://www.w3.org/TR/PNG/#11gAMA
        public const String ID = ChunkHelper.gAMA;
        private double gamma;
	
		public PngChunkGAMA(ImageInfo info) : base(ID, info) {
		}


        public override ChunkOrderingConstraint GetOrderingConstraint()
        {
            return ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT;
        }
		public override ChunkRaw CreateRawChunk() {
			ChunkRaw c = createEmptyChunk(4, true);
			int g = (int) (gamma * 100000 + 0.5d);
			Ar.Com.Hjg.Pngcs.PngHelperInternal.WriteInt4tobytes(g, c.Data, 0);
			return c;
		}

        public override void ParseFromRaw(ChunkRaw chunk)
        {
			if (chunk.Length != 4)
				throw new PngjException("bad chunk " + chunk);
			int g = Ar.Com.Hjg.Pngcs.PngHelperInternal.ReadInt4fromBytes(chunk.Data, 0);
			gamma = ((double) g) / 100000.0d;
		}
	
		public override void CloneDataFromRead(PngChunk other) {
			gamma = ((PngChunkGAMA) other).gamma;
		}
	
		public double GetGamma() {
			return gamma;
		}
	
		public void SetGamma(double gamma_0) {
			this.gamma = gamma_0;
		}
	}
}
