// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkTEXT : PngChunkTextVar {
		public PngChunkTEXT(ImageInfo info) : base(Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.tEXt_TEXT, info) {
		}
	
		public override ChunkRaw CreateChunk() {
			if (val.Length == 0 || key.Length == 0)
				return null;
            byte[] b = Ar.Com.Hjg.Pngcs.PngHelper.charset.GetBytes(key + @"\0" + val);
			ChunkRaw chunk = CreateEmptyChunk(b.Length, false);
			chunk.data = b;
			return chunk;
		}
	
		public override void ParseFromChunk(ChunkRaw c) {
            String[] k = Ar.Com.Hjg.Pngcs.PngHelper.charset.GetString(c.data).Split(new char[]{'\0'});
            key = k[0];
			val = k[1];
		}
	
		public override void CloneDataFromRead(PngChunk other) {
			PngChunkTEXT otherx = (PngChunkTEXT) other;
			key = otherx.key;
			val = otherx.val;
		}
	}
}
