// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:13 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs.Chunks {
	
	using Ar.Com.Hjg.Pngcs;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class PngChunkZTXT : PngChunkTextVar {
		// http://www.w3.org/TR/PNG/#11zTXt
		public PngChunkZTXT(ImageInfo info) : base(Ar.Com.Hjg.Pngcs.Chunks.ChunkHelper.zTXt_TEXT, info) {
		}
	
		public override ChunkRaw CreateChunk() {
			// TODO Implement
			throw new Exception("not implemented");
		}
	
		public override void ParseFromChunk(ChunkRaw c) {
			throw new Exception("not implemented");
		}
	
		public override void CloneDataFromRead(PngChunk other) {
			throw new Exception("not implemented");
		}
	}
}
