// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 6/1/11 9:14 a.m.    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Ar.Com.Hjg.Pngcs {
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	[Serializable]
	public class PngjBadCrcException : PngjException {
		private const long serialVersionUID = 1L;
	
		public PngjBadCrcException(String message, Exception cause) : base(message, cause) {
		}
	
		public PngjBadCrcException(String message) : base(message) {
		}
	
		public PngjBadCrcException(Exception cause) : base(cause) {
		}
	}
}
